# configure
image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"  # cache on project level
cache:
  paths:
    - .cache/pip
    - venv/

# common to all scripts
before_script:
  - python -V
  - pip install -U virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -U twine
  - pip install -U pytest mypy yaqc numpy
  - pip install -e .

# test stage
mypy:
  stage: test
  script:
    - mypy yaqd_core
entry:
  stage: test
  script:
    - yaqd-hardware --version
    - yaqd-hardware -h
    - yaqd-continuous-hardware --version
    - yaqd-continuous-hardware -h

# deploy stage
pages:
  stage: deploy
  script:
  - pip install -U pdoc
  - pdoc --html yaqd_core --html-dir html --overwrite
  - mv html/yaqd_core public
  artifacts:
    paths:
    - public
  only:
    - tags
twine:
  stage: deploy
  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  artifacts:
    paths:
      - dist/*
  only:
    - tags
