repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: no-commit-to-branch
        args: [-b, master]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: black
        entry: black
        require_serial: true
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        exclude: ^docs/conf.py

  - repo: https://gitlab.com/yaq/yaq-traits
    rev: v2021.3.0
    hooks:
      - id: yaq-traits-check
      - id: yaq-traits-compose

