name: mypy

on:
  pull_request:
    types: [opened, reopened]
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.x
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip!=22.1.*
        python -m pip install --upgrade mypy
        python -m pip install .
    - name: Run mypy
      run: |
        mypy yaqd_newport
